id: jbossdemocentral-brms-coolstore
title: JBoss BRMS Cool Store Demo
github_repo_url: https://github.com/jbossdemocentral/brms-coolstore-demo
technologies:
  - RESTful
  - CEP
  - JBoss EAP
  - JBoss BRMS
summary: This is a retail web store demo where you will find rules, decision tables, events, and a ruleflow that is leveraged by a web application. The web application is a WAR built using the JBoss BRMS generated project as a dependency, providing an example project showing how developers can focus on the application code while the business analysts can focus on rules, events, and ruleflows in the JBoss BRMS product web based dashboard. There are three options available to you for using this demo; local, Openshift and Containerized.
level: Beginner
product: brms
author: Jason Milliron, Andrew Block, Eric D. Schabell
